// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * One sidebar, generated from the docs folder: a section per pillar.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  pillarsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
